name: SeleniumTest

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: [self-hosted]
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v5 

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@V1
        with:
          java-version: 25
          maven-version: 3.9.11

      - name: Run the Maven verify phase
        run: mvn test

